version: "3.8"

services:
  database:
    image: quay.io/andrekley/db-card:v1
    environment:
      - MYSQL_ROOT_PASSWORD=root_
      - MYSQL_USER=wpdb
      - MYSQL_PASSWORD=root1
      - MYSQL_DATABASE=wpdb 
    networks:
      - wp_default
    volumes:
      - db_vol:/var/lib/mysql  

  wordpress:
    depends_on:
      - database
    image: quay.io/andrekley/wp-cards:v1
    # ports:
    #   - "8090:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=wpdb
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_PASSWORD=root1  
    volumes:
      - wp_vol:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`planejamentosfacil.com.br`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"
      - "traefik.http.routers.wordpress.tls=true"
    networks:
      - traefik_public
      - wp_default  

networks:
  traefik_public:
    external: true
  wp_default:
    driver: overlay

volumes:
  db_vol:
  wp_vol:
